version: '3'
services:
  server:
    image: ghcr.io/engineering-diploma/pov-server:latest
    environment:
      - RABBIT_HOST=rabbit
      - RABBIT_PORT=5672
      - RABBIT_USERNAME=pov
      - RABBIT_PASSWORD=pov
      - API_USERNAME=test
      - API_PASSWORD=test
      - CONSOLE_USERNAME=console
      - CONSOLE_PASSWORD=console
    ports:
      - 8080:8080
    volumes:
      - server-data:/pov-server/data/

  s3-storage:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - s3-data:/data

#  rabbit:
#    image: tbd

volumes:
  server-data:
  s3-data:
