version: '3'
services:
  server:
    image: pov-server
    environment:
      SPRING_PROFILES_ACTIVE: prod
      RABBIT_HOST: rabbit
      RABBIT_PORT: 5671
      RABBIT_USERNAME: pov
      RABBIT_PASSWORD: pov
      API_USERNAME: test
      API_PASSWORD: test
      CONSOLE_USERNAME: console
      CONSOLE_PASSWORD: console
      CONVERTER_HOME: /pov-server/etc/
      DB_USERNAME: pov
      DB_PASSWORD: pov
      DB_NAME: pov_db
      DB_HOST: database
      DB_PORT: 3306
    ports:
      - 8081:8080
    volumes:
      - server-data:/pov-server/data/

  rabbit:
    image: ghcr.io/engineering-diploma/custom-rabbit-mq:latest
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit-data:/var/lib/rabbitmq

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pov
      MYSQL_DATABASE: pov_db
      MYSQL_USER: pov
      MYSQL_PASSWORD: pov
    ports:
      - 3306:3306
    volumes:
      - database-data:/var/lib/mysql

volumes:
  server-data:
  rabbit-data:
  database-data: