ptl:
  rabbit:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  api:
    username: ${API_USERNAME}
    password: ${API_PASSWORD}
  console:
    username: ${CONSOLE_USERNAME}
    password: ${CONSOLE_PASSWORD}