#spring:
#  datasource:
#    url: "jdbc:mysql://ptl.cloud:3306/pov?ssl=true"
#    password: ""
#    username: "pov"

#ptl:
#  rabbit:
#    host: "ptl.cloud"
#    port: 5671
#    username: "pov"
#    password: ""

#api:
#  username: "api"
#  password: "apidemo"
#console:
#  username: "test"
#  password: "test"