spring:
  datasource:
    username: pov
    password: pov
    url: jdbc:mysql://localhost:3306/pov_db

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


logging:
  level:
    root: info

ptl:
  download:
    youtube: "data/youtube-movies"
    raw: "data/raw"
    converted: "data/converted"

  display:
    diameter: 20

  rabbit:
    host: localhost
    port: 5671
    username: pov
    password: pov
  api:
    username: apitest
    password: apitest
  console:
    username: console
    password: console
