spring:
  profiles:
    active:
      - prod

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info

ptl:
  download:
    youtube: "youtube-movies"
    raw: "raw"
    converted: "converted"

  display:
    diameter: 20
