spring:
  profiles:
    active:
      - prod

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info

ptl:
  download:
    youtube: "youtube-movies"
    gif: "gif"
    gif_converted: "gif-movie"
