spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}

ptl:
  rabbit:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  api:
    username: ${API_USERNAME}
    password: ${API_PASSWORD}
  console:
    username: ${CONSOLE_USERNAME}
    password: ${CONSOLE_PASSWORD}