spring:
  profiles:
    active:
      - prod

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info

ptl:
  download:
    youtube: "data/youtube-movies"
    raw: "data/raw"
    converted: "data/converted"

  display:
    diameter: 20
